openapi: 3.0.0

info:
  title: Kilonova API
  description: OpenAPI specification for Kilonova
  version: 1.0.0

servers:
  - url: http://192.168.122.171/api
    description: Local server

components:
  schemas:
    SessionID:
      type: string
      pattern: "^[0-9a-f]{64}$"
      description: A 32 byte hex-encoded session ID
      example: "6055448870c8f4be345b4d06b1430f9ce97fa09787f380702682ee04a9c4f41d"
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          enum: ["error"]
          description: Indicates the status of the response, which will always be "error"
        data:
          type: string
          description: The human-readable version of the error
      example:
        status: "error"
        data: "Invalid login details"
    LoginResponse:
      type: object
      properties:
        status:
          type: string
          enum: ["success", "error"]
          description: Indicates the status of the login request ("success" or "error")
        data:
          $ref: "#/components/schemas/SessionID"
      example:
        status: "success"
        data: "29dafb5f606742b706a6f7fc5a1c83dc98470db1a1110cf8c8dcbcdff276dce1"

paths:
  /auth/login:
    post:
      summary: Log in to Kilonova
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's email address or username
                  example: acmecorp
                password:
                  type: string
                  format: password
                  description: User's password
                  example: K110N0va
            examples:   
              Valid login request (username and password):
                value:
                  username: mircea
                  password: geoana2009
              Valid login request (email and password):
                value:
                  username: nadia@comaneci.ro
                  password: montreal1976
              Invalid credentials (wrong username or password):
                value:
                  username: doesnt@exist.com
                  password: incorrect_password
              Empty username:
                value:
                  username: 
                  password: parola123  
              Empty password:
                value:
                  username: bacau
                  password:       
      responses:
        "200":
          description: Successful login response, with the session ID autogenerated for the new account.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
              example:
                status: "success"
                data: "086bcf5921ad3e02d18e2af9ff660a89838926a5a4f2d53fa7c2ae35151a4204"    
        "400":
          description: Bad request, indicating invalid login details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Invalid credentials (wrong username or password):
                  value:
                    status: "error"
                    data: "Invalid login details"
                Empty username:
                  value:
                    status: "error"
                    data: "Invalid login details"
                Empty password:
                  value:
                    status: "error"
                    data: "Invalid login details"